//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBillingReportRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentProfile()
        {
            this.UserAccount = new HashSet<UserAccount>();
        }
    
        public System.Guid ID { get; set; }
        public string CebuPacific { get; set; }
        public string AirAsia { get; set; }
        public string IASA { get; set; }
        public string IATA { get; set; }
        public string PAL { get; set; }
        public string CebuPacificSafeName { get; set; }
        public string AirAsiaSafeName { get; set; }
        public string IASASafeName { get; set; }
        public string IATASafeName { get; set; }
        public string PALSafeName { get; set; }
        public string Department { get; set; }
        public string Name { get; set; }
        public string SafeName { get; set; }
        public string TravCom1 { get; set; }
        public string TravCom2 { get; set; }
        public string TravCom3 { get; set; }
        public string TravCom4 { get; set; }
        public string TravCom5 { get; set; }
        public string Parameter { get; set; }
        public string PartnerAgent { get; set; }
        public string PartnerAgentSafeName { get; set; }
        public string ClientPartnerAgent { get; set; }
        public string ClientPartnerAgentSafeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccount { get; set; }
    }
}
