//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBillingReportRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AirlineBillingReportEntities : DbContext
    {
        public AirlineBillingReportEntities()
            : base("name=AirlineBillingReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentProfile> AgentProfile { get; set; }
        public virtual DbSet<AirlineConfiguration> AirlineConfiguration { get; set; }
        public virtual DbSet<BilledTicket> BilledTicket { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<IATA> IATA { get; set; }
        public virtual DbSet<LoginLogs> LoginLogs { get; set; }
        public virtual DbSet<NoRecord> NoRecord { get; set; }
        public virtual DbSet<RecordNoStorage> RecordNoStorage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnbilledTicket> UnbilledTicket { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<PAL_APAnalysis> PAL_APAnalysis { get; set; }
        public virtual DbSet<AEFURNoRecord> AEFURNoRecord { get; set; }
        public virtual DbSet<GetAllUnbilled> GetAllUnbilled { get; set; }
        public virtual DbSet<GetAllVoided> GetAllVoided { get; set; }
        public virtual DbSet<IASA_APAnalysis> IASA_APAnalysis { get; set; }
        public virtual DbSet<C5J_APAnalysis> C5J_APAnalysis { get; set; }
        public virtual DbSet<AEFURUnbilled> AEFURUnbilled { get; set; }
    
        public virtual ObjectResult<BilledSummaryReport_Result> BilledSummaryReport(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BilledSummaryReport_Result>("BilledSummaryReport", recordNoParameter);
        }
    
        public virtual ObjectResult<UnbilledSummaryReport_Result> UnbilledSummaryReport(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnbilledSummaryReport_Result>("UnbilledSummaryReport", recordNoParameter);
        }
    
        public virtual ObjectResult<NoRecordSummaryReport_Result> NoRecordSummaryReport(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NoRecordSummaryReport_Result>("NoRecordSummaryReport", recordNoParameter);
        }
    
        public virtual ObjectResult<UnbilledMonitoringByAgent_Result> UnbilledMonitoringByAgent(string travCom1, string travCom2, string travCom3, string travCom4, string travCom5)
        {
            var travCom1Parameter = travCom1 != null ?
                new ObjectParameter("TravCom1", travCom1) :
                new ObjectParameter("TravCom1", typeof(string));
    
            var travCom2Parameter = travCom2 != null ?
                new ObjectParameter("TravCom2", travCom2) :
                new ObjectParameter("TravCom2", typeof(string));
    
            var travCom3Parameter = travCom3 != null ?
                new ObjectParameter("TravCom3", travCom3) :
                new ObjectParameter("TravCom3", typeof(string));
    
            var travCom4Parameter = travCom4 != null ?
                new ObjectParameter("TravCom4", travCom4) :
                new ObjectParameter("TravCom4", typeof(string));
    
            var travCom5Parameter = travCom5 != null ?
                new ObjectParameter("TravCom5", travCom5) :
                new ObjectParameter("TravCom5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnbilledMonitoringByAgent_Result>("UnbilledMonitoringByAgent", travCom1Parameter, travCom2Parameter, travCom3Parameter, travCom4Parameter, travCom5Parameter);
        }
    
        public virtual ObjectResult<UnbilledMonitoringByManager_Result> UnbilledMonitoringByManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnbilledMonitoringByManager_Result>("UnbilledMonitoringByManager");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<DebitMemoIATA_Result> DebitMemoIATA(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DebitMemoIATA_Result>("DebitMemoIATA", recordNoParameter);
        }
    
        public virtual ObjectResult<RefundsIATA_Result> RefundsIATA(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RefundsIATA_Result>("RefundsIATA", recordNoParameter);
        }
    
        public virtual ObjectResult<TicketedIATA_Result> TicketedIATA(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TicketedIATA_Result>("TicketedIATA", recordNoParameter);
        }
    
        public virtual ObjectResult<UnpostedIATA_Result> UnpostedIATA(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnpostedIATA_Result>("UnpostedIATA", recordNoParameter);
        }
    
        public virtual ObjectResult<DebitMemoIATAUSD_Result> DebitMemoIATAUSD(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DebitMemoIATAUSD_Result>("DebitMemoIATAUSD", recordNoParameter);
        }
    
        public virtual ObjectResult<RefundsIATAUSD_Result> RefundsIATAUSD(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RefundsIATAUSD_Result>("RefundsIATAUSD", recordNoParameter);
        }
    
        public virtual ObjectResult<TicketedIATAUSD_Result> TicketedIATAUSD(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TicketedIATAUSD_Result>("TicketedIATAUSD", recordNoParameter);
        }
    
        public virtual ObjectResult<UnpostedIATAUSD_Result> UnpostedIATAUSD(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnpostedIATAUSD_Result>("UnpostedIATAUSD", recordNoParameter);
        }
    
        public virtual ObjectResult<PostedPALAP_Result> PostedPALAP(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostedPALAP_Result>("PostedPALAP", recordNoParameter);
        }
    
        public virtual ObjectResult<UnpostedPALAP_Result> UnpostedPALAP(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnpostedPALAP_Result>("UnpostedPALAP", recordNoParameter);
        }
    
        public virtual ObjectResult<PostedIASAAP_Result> PostedIASAAP(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostedIASAAP_Result>("PostedIASAAP", recordNoParameter);
        }
    
        public virtual ObjectResult<UnpostedIASAAP_Result> UnpostedIASAAP(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UnpostedIASAAP_Result>("UnpostedIASAAP", recordNoParameter);
        }
    
        public virtual ObjectResult<Posted5JAP_Result> Posted5JAP(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Posted5JAP_Result>("Posted5JAP", recordNoParameter);
        }
    
        public virtual ObjectResult<Unposted5JAP_Result> Unposted5JAP(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Unposted5JAP_Result>("Unposted5JAP", recordNoParameter);
        }
    
        public virtual ObjectResult<CreditMemoIATA_Result> CreditMemoIATA(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreditMemoIATA_Result>("CreditMemoIATA", recordNoParameter);
        }
    
        public virtual ObjectResult<CreditMemoIATAUSD_Result> CreditMemoIATAUSD(string recordNo)
        {
            var recordNoParameter = recordNo != null ?
                new ObjectParameter("RecordNo", recordNo) :
                new ObjectParameter("RecordNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreditMemoIATAUSD_Result>("CreditMemoIATAUSD", recordNoParameter);
        }
    }
}
