//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBillingReportRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineConfiguration
    {
        public string Airline { get; set; }
        public Nullable<int> StartRow { get; set; }
        public string StartColumn { get; set; }
        public string AgentCodeCol { get; set; }
        public string FirstNameCol { get; set; }
        public string RecordLocatorCol { get; set; }
        public string CreatedOrganizationCol { get; set; }
        public string SourceOrganizationCodeCol { get; set; }
        public string PaymentCodeCol { get; set; }
        public string PaymentIDCol { get; set; }
        public string AuthorizationStatusCol { get; set; }
        public string CurrencyCodeCol { get; set; }
        public string BookingAmountCol { get; set; }
        public string CollectedCurrencyCodeCol { get; set; }
        public string CollectedAmountCol { get; set; }
        public string ConvertedCurrencyCodeCol { get; set; }
        public string ConvertedAmountCol { get; set; }
        public string PaymentText { get; set; }
        public string PassengerFirstName { get; set; }
        public string PassengerLastName { get; set; }
        public string RouteDeparture { get; set; }
        public string RouteDestination { get; set; }
        public string LastNameCol { get; set; }
        public string PaymentDate { get; set; }
        public string TabName { get; set; }
        public string AirlineCode { get; set; }
        public string TicketNo { get; set; }
    }
}
