//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBillingReportRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilledTicket
    {
        public System.Guid ID { get; set; }
        public string DateRange { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public string RecordLocator { get; set; }
        public string SourceOrganizationCode { get; set; }
        public string PaymentCode { get; set; }
        public string PaymentID { get; set; }
        public string AuthorizationStatus { get; set; }
        public string CreatedOrganizationCode { get; set; }
        public string CurrencyCode { get; set; }
        public string BookingAmount { get; set; }
        public string CollectedCurrencyCode { get; set; }
        public string CollectedAmount { get; set; }
        public string ConvertedCurrencyCode { get; set; }
        public string PaymentText { get; set; }
        public string PassengerName { get; set; }
        public string DepartureCity { get; set; }
        public string DestinationCity { get; set; }
        public string Airline { get; set; }
        public string ConvertedAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string RecordNo { get; set; }
        public string InvoiceNo { get; set; }
        public string TicketNo { get; set; }
        public string InvoiceDate { get; set; }
        public string AirlineCode { get; set; }
        public string ExchangeRate { get; set; }
        public string ClientName { get; set; }
        public string Department { get; set; }
    
        public virtual RecordNoStorage RecordNoStorage { get; set; }
    }
}
