//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBillingReportRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class C5J_APAnalysis
    {
        public System.Guid ID { get; set; }
        public string DateRange { get; set; }
        public string AgentCode { get; set; }
        public string TCName { get; set; }
        public string RecordLocator { get; set; }
        public string PaymentCode { get; set; }
        public string PaymentID { get; set; }
        public string AuthorizationStatus { get; set; }
        public string ConvertedCurrency { get; set; }
        public Nullable<decimal> ConvertedAmount { get; set; }
        public string PassengerName { get; set; }
        public string Itinerary { get; set; }
        public string InvoiceNo { get; set; }
        public string ClientName { get; set; }
        public string IsPosted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string RecordNo { get; set; }
    }
}
