//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBillingReportRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public System.Guid ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
        public string Airline { get; set; }
        public string Type { get; set; }
        public string RecordLocator { get; set; }
        public string RecordNo { get; set; }
    
        public virtual RecordNoStorage RecordNoStorage { get; set; }
    }
}
