//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBillingReportRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAllUnbilled
    {
        public string RecordLocator { get; set; }
        public Nullable<byte> TransactionType { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string ProfileName { get; set; }
        public string PassengerName { get; set; }
        public string TicketNumber { get; set; }
        public string BookingAgentNumber { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string CurrencyCode { get; set; }
        public string DepartureCityCode { get; set; }
        public string ArrivalCityCode { get; set; }
        public string AirlineCode { get; set; }
        public string VendorNumber { get; set; }
        public string FullName { get; set; }
        public string TravCom1 { get; set; }
        public string TravCom2 { get; set; }
        public string TravCom3 { get; set; }
        public string TravCom4 { get; set; }
        public string TravCom5 { get; set; }
        public string Department { get; set; }
        public string Name { get; set; }
    }
}
