//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineBillingReportRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAL_APAnalysis
    {
        public System.Guid ID { get; set; }
        public string DateOfIssue { get; set; }
        public string Carrier { get; set; }
        public string PassengerName { get; set; }
        public string TicketNo { get; set; }
        public string FareSource { get; set; }
        public string SaleStatus { get; set; }
        public string RecordLocator { get; set; }
        public string Seg { get; set; }
        public string Itinerary { get; set; }
        public string IATANo { get; set; }
        public string SignInCode { get; set; }
        public string TCName { get; set; }
        public string Remarks { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
        public Nullable<decimal> NetFare { get; set; }
        public Nullable<decimal> Payable { get; set; }
        public string FlightNumber { get; set; }
        public string DepartureDate { get; set; }
        public string TourCode { get; set; }
        public string BookingClass { get; set; }
        public string FareBasisCode { get; set; }
        public string TaxBreakdown { get; set; }
        public Nullable<decimal> PD { get; set; }
        public Nullable<decimal> LI { get; set; }
        public Nullable<decimal> PV { get; set; }
        public Nullable<decimal> OD { get; set; }
        public Nullable<decimal> NS { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> CA { get; set; }
        public decimal XG { get; set; }
        public Nullable<decimal> SQ { get; set; }
        public string InvoiceNo { get; set; }
        public string Post { get; set; }
        public string ClientName { get; set; }
        public string IsPosted { get; set; }
        public string Market { get; set; }
        public Nullable<decimal> RC { get; set; }
        public string RecordNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
